version: "3"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./pipelines:/var/jenkins_home/pipelines
      - ./init_scripts:/var/jenkins_home/init.groovy.d
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
